### ISSUE TITLE
[feature] tag and CSS selector for color and attachment control style

### ISSUE THREAD

**Issue by Thaina** [EsotericSoftware/spine-runtimes#2009]
Sometimes we have multiple parts that want to be changed to the same property at runtime, such as skin or shirt color and attachment id. And these property might be mixed

So I wish we could have artist tag the slot for marking color of each part that should be the same, and in the runtime programmer could query all those slots with the same tag and apply the same color or other property such as attachment for slot

And I would also suggest that, with tag and as a css class and name of slot as css type, spine runtime API could support applying css or a data structure that parsable from css

Something like this

```css
.skin {
    color : brown;
}

.shape {
    attachment: muscular; /* attachment slot ID */
}

chest_tattoo { /* not a tag but the name of slot */
    color : black;
    attachment: dragon;
}
```

The `skin` tag might be apply to face, arm, hand, leg but not body and `shape` tag might apply to body, arm, leg but not face and hand. While body, arm, leg would all have attachments name muscular, normal, skinny, fat provided

With these features, skeleton API should have function `IEnumerable<Slot> FindSlotsWithSelector(string selector)` that would return each slot object that match css selector. And `void Apply(string[] css)` that could input full css like above sample into skeleton

```C#
skeletonAnimation.skeleton.Apply(".skin { color : brown; }",".shape { attachment: muscular; }");
```

Something like this
